apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Type set to NodePort to expose externally
  selector:
    app: nginx
  ports:
    - port: 80  # Port inside the cluster
      targetPort: 80  # Port to forward traffic to in the container
      nodePort: 30007  # External port on which the service will be accessible
